import {StyleSheet} from 'react-native';
import {theme} from '../../../theme';
import colors from '../../../theme/colors';
import fonts from '../../../theme/fonts';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.colorPrimary,
    paddingTop: Platform.OS === 'ios' ? 44 : 0,
  },
  scheduleBtn: {
    height: 50,
    width: '90%',
    backgroundColor: theme.colors.colorPrimary,
    borderRadius: 10,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginVertical: 40,
    paddingHorizontal: 20,
  },
  InvitedUserFlatlistContainer: {
    height: 150,
    backgroundColor: theme.colors.grey_shade_4,
    borderRadius: 10,
    marginTop: 10,
  },
  textArea: {
    height: 150,
    justifyContent: 'flex-start',
    fontSize: 16,
    lineHeight: 19,
    color: theme.colors.black,
    // paddingStart: 10,
  },
  addbtn: {
    backgroundColor: '#73C1DE',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    marginTop: 15,
    paddingVertical: 5,
    paddingHorizontal: 20,
  },
  inviteBtn: {
    height: 30,
    backgroundColor: '#73C1DE',
    borderRadius: 5,
    justifyContent: 'center',
    alignItems: 'center',
    alignSelf: 'center',
    paddingHorizontal: 10,
    marginVertical: 20,
  },
  input: {
    fontSize: 18,
    paddingHorizontal: 10,
    paddingVertical: 12,
    borderRadius: 10,
    minHeight: 50,
  },
  image: {
    position: 'absolute',
    alignSelf: 'flex-end',
  },
  modalView: {
    flex: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#d3d3d3C2',
  },
  inviteEmail: {
    width: '80%',
    color: theme.colors.black,
    fontSize: 14,
    fontFamily: theme.fonts.SFProRegular,
    paddingLeft: 7,
    paddingRight: 7,
    borderRadius: 5,
    borderWidth: 1,
    paddingVertical: 5,
    borderColor: '#9FA2B4',
  },
  modalContanier: {
    width: '90%',
    maxHeight: '70%',
    backgroundColor: 'white',
    borderRadius: 20,
    overflow: 'hidden',
  },
  modalHeader: {
    backgroundColor: '#EBEDF0',
    width: '100%',
    borderTopEndRadius: 20,
    borderTopLeftRadius: 20,
  },
  modalHeaderText: {
    fontSize: 18,
    color: '#000000',
    textAlign: 'center',
    padding: 5,
  },
  inviteEmailContainer: {
    width: '100%',
    flexDirection: 'row',
    paddingHorizontal: 20,
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 50,
  },
  modalBtnContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 50,
  },
  modalBtn: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnText: {
    fontWeight: '600',
    color: '#FFFFFF',
    fontSize: 14,
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
  spinnerTextStyle: {
    color: '#FFF',
  },
  imageStyle: {
    height: 50,
    width: 50,
    borderRadius: 25,
    marginEnd: 10,
  },

  itemContainer: {
    marginTop: 10,
    paddingTop: 10,
    paddingBottom: 5,
    paddingHorizontal: 10,
    borderRadius: 10,
    backgroundColor: colors.white,
    marginHorizontal: 10,
    elevation: 5,
    shadowColor: colors.black,
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 1},
    shadowRadius: 10,
  },
  itemHeader: {
    flexDirection: 'row',
    width: '100%',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  onlineView: {
    backgroundColor: colors.colorPrimary,
    height: 16,
    width: 16,
    borderRadius: 8,
  },

  offlineView: {
    backgroundColor: colors.red_shade_1,
    height: 16,
    width: 16,
    borderRadius: 8,
  },
  nameStyle: {
    fontSize: 17,
    fontWeight: 'bold',
    width: '90%',
    marginBottom: 5,
  },
  emailTextStyle: {
    fontSize: 16,
    fontFamily: fonts.SFProMedium,
    color: colors.black,
    width: '100%',
    marginBottom: 5,
  },
  headerContainer: {
    width: '100%',
    backgroundColor: '#C5C7CD',
    paddingVertical: 5,
    justifyContent: 'center',
    alignItems: 'center',
  },
  selectContactStyle: {
    fontSize: 20,
    fontFamily: fonts.SFProRegular,
  },
  genrateContainer: {
    //borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 7,
    paddingRight: 7,
    marginTop: 10,
    height: 50,
    width: '100%',
    justifyContent: 'space-between',
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: theme.colors.grey_shade_4,
  },
  genrateButtonContainer: {
    borderRadius: 10,
    height: '70%',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.grey_shade_1,
  },
  genrateText: {
    fontSize: 16,
    paddingHorizontal: 10,
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProRegular,
  },
  codeTextStyle: {
    fontSize: 17,
    paddingStart: 5,
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProMedium,
  },
  EmailTitleStyle: {
    fontSize: 14,
    fontFamily: theme.fonts.SFProMedium,
    color: theme.colors.black,
  },
  invitedUserTextStyle: {
    fontSize: 17,
    fontFamily: theme.fonts.SFProRegular,
    color: theme.colors.black,
    paddingVertical: 2
  },
  invitedUserListItemStyle: {
    marginVertical: 5,
    backgroundColor: theme.colors.white,
    paddingVertical: 15,
    borderRadius: 5,
    borderWidth: 0.7,
    paddingHorizontal: 15,
    borderColor: theme.colors.grey_shade_1,
  },
  iconContainer: {
    flexDirection: 'row',
    justifyContent: 'space-evenly',
    marginTop: 20,
    paddingHorizontal: 10,
  },
  iconbg: {
    backgroundColor: theme.colors.colorPrimary,
    borderRadius: 18,
    height: 36,
    width: 36,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateIconContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  flatlistContainer: {
    paddingVertical: 15,
    paddingHorizontal: 10,
  },
  emptyInvitedUserList: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyInvitedUserListText: {
    fontSize: 16,
    fontFamily: theme.fonts.SFProRegular,
    color: theme.colors.black,
  },
  searchBarContainer: {
    borderWidth: 0.6,
    borderColor: colors.black,
    borderRadius: 5,
  },
});
const scheduleCallStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.colorPrimary,
    paddingTop: Platform.OS === 'ios' ? 44 : 0,
  },
  scheduleBtn: {
    height: 50,
    backgroundColor: theme.colors.colorPrimary,
    borderRadius: 20,
    padding: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  root: {
    width: '95%',
    alignSelf: 'center',
    flexDirection: 'row',
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    backgroundColor: theme.colors.grey_shade_4,
    borderRadius: 12,
    padding: 10,
    marginTop: 20,
  },
  name: {
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProRegular,
    fontSize: 18,
    flexGrow: 1,
    fontWeight: 'bold',
  },
  detail: {
    color: 'rgba(0,0,0, 0.48)',
    fontFamily: theme.fonts.SFProRegular,
    fontSize: 15,
    flexGrow: 1,
    marginTop: 10,
  },
  image: {
    alignSelf: 'center',
  },
  spinnerTextStyle: {
    color: '#FFF',
  },
  emptyScheduleCallList: {
    height: '100%',
    width: '100%',
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyScheduleTextStyle: {
    fontSize: 18,
    fontFamily: theme.fonts.SFProMedium,
    color: theme.colors.black,
  },
  scheduleCallButton: {
    height: '10%',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
const scheduleCallDetailStyle = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.colorPrimary,
    paddingTop: Platform.OS === 'ios' ? 44 : 0,
  },
  btn: {
    height: 40,
    width: 120,
    borderRadius: 10,
    justifyContent: 'center',
    alignItems: 'center',
  },
  inerContainer: {
    width: '92%',
    alignSelf: 'center',
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    paddingHorizontal: 15,
    marginTop: 30,
    paddingVertical: 25,
    elevation: 5,
    shadowColor: 'black',
    shadowOpacity: 0.2,
    shadowOffset: {width: 0, height: 0},
    shadowRadius: 12,
    marginBottom: 0,
  },
  title: {
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProRegular,
    fontSize: 16,
    flexGrow: 1,
    fontWeight: 'bold',
    alignSelf: 'center',
  },
  detail: {
    color: 'rgba(0,0,0, 0.48)',
    fontFamily: theme.fonts.SFProMedium,
    fontSize: 18,
    marginTop: 10,
  },
  btnContainer: {
    width: '95%',
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignSelf: 'center',
    marginTop: 40,
  },
  btnText: {
    fontSize: 18,
    color: '#FFFFFF',
    fontFamily: fonts.SFProRegular,
  },
  modalView: {
    flex: 4,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#d3d3d3C2',
  },
  modalContanier: {
    width: '90%',
    maxHeight: '70%',
    backgroundColor: 'white',
    borderRadius: 20,
  },
  modalHeader: {
    backgroundColor: '#EBEDF0',
    width: '100%',
    borderTopEndRadius: 20,
    borderTopLeftRadius: 20,
  },
  modalHeaderText: {
    fontFamily: fonts.SFProBold,
    fontSize: 20,
    color: '#000000',
    alignSelf: 'center',
    paddingVertical: 5,
  },
  modalText: {
    fontFamily: fonts.SFProRegular,
    fontSize: 20,
    color: '#000000',
    alignSelf: 'center',
    textAlign: 'center',
  },
  inviteEmailContainer: {
    paddingTop: 15,
  },
  modalBtnContainer: {
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginTop: 50,
  },
  modalBtn: {
    borderRadius: 5,
    alignItems: 'center',
    justifyContent: 'center',
  },
  modalBtnText: {
    fontWeight: '600',
    color: '#FFFFFF',
    fontSize: 14,
    paddingHorizontal: 30,
    paddingVertical: 10,
  },
  spinnerTextStyle: {
    color: '#FFF',
  },
  participantTextStyle: {
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProRegular,
    fontSize: 16,
    marginVertical: 10,
    fontWeight: 'bold',
    marginTop: 20,
  },
  visitDetailStyle: {
    alignSelf: 'center',
    fontSize: 17,
    color: theme.colors.black,
    fontFamily: theme.fonts.SFProRegular,
    marginBottom: 30,
    marginTop: 5,
  },
  participantContainer: {
    padding: 5,
    borderWidth: 1,
    marginBottom: 10,
    borderRadius: 5,
    width: '49%',
    borderColor: colors.colorPrimary,
  },
  iconContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    paddingHorizontal: 10,
  },
  iconbg: {
    backgroundColor: theme.colors.colorPrimary,
    borderRadius: 15,
    height: 30,
    width: 30,
    justifyContent: 'center',
    alignItems: 'center',
  },
  dateTimeStyle: {
    fontSize: 17,
    fontFamily: fonts.SFProRegular,
    marginTop: 20,
    alignSelf: 'center',
    color: colors.black,
  },
  noParticipantStyle: {
    fontSize: 17,
    fontFamily: fonts.SFProMedium,
    marginTop: 5,
    alignSelf: 'center',
    color: colors.black,
  },
});
export {styles, scheduleCallStyle, scheduleCallDetailStyle};
